services:
    :
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - POKEAPI_HOST=pokeapi.co
      - POKEAPI_SECURE=true
      - FUN_TRANSLATIONS_HOST=api.funtranslations.com
      - FUN_TRANSLATIONS_SECURE=true
    restart: unless-stopped
